apiVersion: v1
kind: Service
metadata:
  name: ecomm-app-service
spec:
  type: NodePort
  selector:
    app: ecomm-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30036  # You can customize this port

