apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cafe-nodejs-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cafe-nodejs-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metric:
        name: istio_requests_total
      target:
        type: AverageValue
        averageValue: "5"

