apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: proxysql
  labels:
    release: prometheus  # 👈 must match Prometheus release
spec:
  selector:
    matchLabels:
      app: proxysql
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s

