apiVersion: v1
kind: ConfigMap
metadata:
  name: proxysql-config
data:
  proxysql.cnf: |
    datadir="/var/lib/proxysql"

    admin_variables=
    {
      admin_credentials="admin:admin"
      mysql_ifaces="0.0.0.0:6032"
    }

    mysql_variables=
    {
      threads=4
      max_connections=2048
      monitor_username = "monitor"
      monitor_password = "monitorpass"
      monitor_connect_interval = 2000
      monitor_ping_interval = 10000
      monitor_read_only_interval = 1500
      monitor_replication_lag_interval = 10000
    }

    mysql_servers =
    (
      { address = "mysql-master-0.mysql.default.svc.cluster.local", port = 3306, hostgroup = 10, max_connections=100 },
      { address = "mysql-slave-0.mysql.default.svc.cluster.local", port = 3306, hostgroup = 20, max_connections = 100, weight = 100, max_replication_lag = 10 },
      { address = "mysql-slave-1.mysql.default.svc.cluster.local", port = 3306, hostgroup = 20, max_connections = 100, weight = 50, max_replication_lag = 10 }
    )

    mysql_users =
    (
      { username = "test", password = "testpass", default_hostgroup = 10, active = 1 }
    )

    # Optional: query rules for a single shared user (if needed)
    mysql_query_rules =
    (
      {
        rule_id = 1,
        active = 1,
        match_pattern = "^SELECT .*",
        destination_hostgroup = 20,
        apply = 1
      },
      {
        rule_id = 2,
        active = 1,
        match_pattern = ".*",
        destination_hostgroup = 10,
        apply = 1
      }
    )

