apiVersion: v1
kind: Service
metadata:
  name: proxysql
  labels:
    app: proxysql
    release: prometheus  # 👈 must match your Prometheus release name
spec:
  selector:
    app: proxysql
  ports:
  - name: mysql-client
    port: 6033
    targetPort: 6033
  - name: admin
    port: 6032
    targetPort: 6032
  - name: metrics
    port: 42004
    targetPort: 42004

