apiVersion: v1
kind: Service
metadata:
  name: proxysql
spec:
  selector:
    app: proxysql
  ports:
  - name: mysql-client
    port: 6033
    targetPort: 6033
  - name: admin
    port: 6032
    targetPort: 6032

