apiVersion: v1
kind: Service
metadata:
  name: mysql-write
  labels:
    role: master
spec:
  selector:
    app: mysql
    role: master
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306

