apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  clusterIP: None  # 👈 headless!
  selector:
    app: nginx
  ports:
    - name: web
      port: 80
      targetPort: 80

