apiVersion: v1
kind: Pod
metadata:
  name: load-generator
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: ["/bin/sh", "-c"]
    args:
      - |
        while true; do
          curl -s http://172.16.51.60.nip.io:30687 > /dev/null
          sleep 0.1
        done
  restartPolicy: Never

