apiVersion: v1
kind: Pod
metadata:
  name: webapp-with-init
spec:
  initContainers:
  - name: wait-for-mysql
    image: busybox
    command: ['sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done;']
  
  containers:
  - name: webapp
    image: php:8.1-apache
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /var/www/html

  - name: redis
    image: redis:alpine
    ports:
    - containerPort: 6379

  volumes:
  - name: html
    emptyDir: {}

